name: Type-Check

on:
  push:
  pull_request:

jobs:
  type-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Static type checking with mypy
      run: |
        mypy . --explicit-package-bases
